#!/bin/zsh
set -euo pipefail

SCUA_ROOT="${0:A:h:h}"
export PI_COMPUTER_USE_HEADLESS="false"
export PI_COMPUTER_USE_CURSOR_OVERLAY="true"
export PI_COMPUTER_USE_EXECUTION_MODE="${PI_COMPUTER_USE_EXECUTION_MODE:-background}"
export PI_COMPUTER_USE_USER_QUIET_PERIOD_MS="${PI_COMPUTER_USE_USER_QUIET_PERIOD_MS:-750}"
export PI_COMPUTER_USE_USER_ACTIVITY_TIMEOUT_MS="${PI_COMPUTER_USE_USER_ACTIVITY_TIMEOUT_MS:-5000}"

exec /usr/bin/env node "${SCUA_ROOT}/mcp/server.ts"
